FROM node:18

# Définir le répertoire de travail
WORKDIR /app

# Installer expo-cli globalement
RUN yarn global add expo-cli

# Installer watchman (important pour React Native)
RUN apt-get update && apt-get install -y \
    watchman \
    && rm -rf /var/lib/apt/lists/*

# Copier package.json et yarn.lock
COPY package.json yarn.lock ./

# Installer les dépendances
RUN yarn install 

# Copier le reste du code
COPY . .

# Variables d'environnement utiles pour Expo
ENV EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
ENV REACT_NATIVE_PACKAGER_HOSTNAME=localhost

# Exposer les ports Expo
EXPOSE 19000 19001 19002 8081

# Lancer Expo en mode dev
CMD ["yarn", "start"]