# Utilisation de l'image Python officielle
FROM python:3.10

RUN apt-get update && apt-get install -y netcat-openbsd

# Définir le répertoire de travail
WORKDIR /app

# Copier les fichiers du projet dans le conteneur
COPY . .
COPY wait-for-db.sh ./
RUN chmod +x wait-for-db.sh

# Installer les dépendances
RUN pip install --upgrade pip
RUN pip install -r requirements.txt



# Exposer le port 8000 pour Django
EXPOSE 8000

# Commande pour démarrer le serveur Django
CMD ["./wait-for-db.sh","python", "manage.py", "runserver", "0.0.0.0:8000"]